### ISSUE TITLE
Arm stls changed?

### ISSUE THREAD

**Issue by RURon** [jscancella/vcore3_modifications#1]
Hello, I think the arm stls are different and there are problems with the boolean operations:

![grafik](https://user-images.githubusercontent.com/17233445/145086604-924535f5-101e-4a38-b9d8-9927dcf06725.png)

**Comment by jscancella** [comment]
Not sure what the problem is. The arms are from https://www.thingiverse.com/thing:5131325

**Comment by mmirate** [comment]
Interesting. The models now available from that page, differ significantly from the illustrations on that page.

**Comment by jscancella** [comment]
> Interesting. The models now available from that page, differ significantly from the illustrations on that page.

sorry but I don't understand what you mean

**Comment by mmirate** [comment]
The new stylized cutouts which produce the structural problems as seen on the image on this issue post, do not appear in the illustrations at https://www.thingiverse.com/thing:5131325, even though they are present in the STLs that are available for download for https://www.thingiverse.com/thing:5131325.

**Comment by jscancella** [comment]
Why do you need to fill in those cutouts? They don't affect the printed part

**Comment by mmirate** [comment]
Some of the resulting geometry, especially the one appearing top-right in the image, clearly has much thinner walls than it would normally have; I'm worried it will break (or bend) much sooner than normal.

**Comment by jscancella** [comment]
But the forces are up and down, so it doesn't matter that the walls are thinner.
@RURon please reopen if you are still having an issue
